### ISSUE TITLE
Unable to add sensor.yield today to energy dashboard

### ISSUE THREAD

**Issue by mooi-zestien** [frank8the9tank/Home-assistant-Solax-cloud#7]
Unable to add sensor.yield today to energy dashboard (ADD SOLAR PRODUCTION)

State: sensor.yield_today

unit_of_measurement: kWh
device_class: energy
friendly_name: Solax today

In the Configure solar panels ( ADD SOLAR PRODUCTION ) sensor.yield_today is not found.
https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities

Core 2024.11.3
Supervisor 2024.11.4
Operating System 14.0 also older versions.
Frontend 20241106.2

**Comment by mooi-zestien** [comment]
In de Home assistent database I found no state of statistics for variable looks like "cloud" or "solax" 
The only variable I found was "update.solax_cloud_update"

**Comment by webpatrick** [comment]
Could it be that it's missing a state_class attribute?
Should be total_increasing because the sensor resets itself every day.

**Comment by webpatrick** [comment]
@frank8the9tank 
Maybe add the state_class attribute to more sensors. Take a look at the [Solax Power intagration](https://github.com/home-assistant/core/blob/dev/homeassistant/components/solax/sensor.py) for inspiration.

**Comment by mooi-zestien** [comment]
> [@frank8the9tank](https://github.com/frank8the9tank) Maybe add the state_class attribute to more sensors. Take a look at the [Solax Power intagration](https://github.com/home-assistant/core/blob/dev/homeassistant/components/solax/sensor.py) for inspiration.

"state_class: total_increasing" right that was the correct solution!

**Comment by remopini** [comment]
How do you add "state_class: total_increasing" to the sensor.yield_today persistently? Whenever I add it in developer tools, it gets removed after a while...

**Comment by lswist** [comment]
There is only one entity available in the integration, named: 
Solax cloud update

It does nothing, shows nothing as well.

**Comment by flight1wer1** [comment]
@mooi-zestien can you may explain, how you have got the state_class into Yield Today entity? Thanks so much for your help

**Comment by flight1wer1** [comment]
@frank8the9tank , is it possible to change or add the state class in the sensor.yaml? I have tried it, but then i get an error in the repository. May you can help, that the yield Today can be implemented in the Energy dashboard

**Comment by mooi-zestien** [comment]
> [@mooi-zestien](https://github.com/mooi-zestien) can you may explain, how you have got the state_class into Yield Today entity? Thanks so much for your help

Hi @flight1wer1 , I used this config configuration.yaml

Then I used "solar_today" to add to dashboard Energy / Solar panels

Hope this helps.

**configuration.yaml**

The dots are "-" !!
template:
  - sensor:
    - name: "solax_energy"
      unique_id: 0a27984d-Uniek-540e776f2df0
      device_class: energy
      unit_of_measurement: 'kWh'
      state_class: total_increasing
      state: >
            {% if is_state('sensor.yield_total', 'unavailable') %}{{none}}{% else %}
            {{ ((states('sensor.yield_total') | float(default=0)) / 1) | round(2, default=0) }}
            {% endif %}
  - sensor:
    - name: "solax_today"
      unique_id: 0a27984d-Uniek-540e776f2df1
      device_class: energy
      unit_of_measurement: 'kWh'
      state_class: total_increasing
      state: >
            {% if is_state('sensor.yield_today', 'unavailable') %}{{none}}{% else %}
            {{ ((states('sensor.yield_today') | float(default=0)) / 1) | round(2, default=0) }}
            {% endif %}

**Comment by flight1wer1** [comment]
Thanks so much for your help!!
Works great!!

Best regards from Austria
T

Am Mo., 11. Aug. 2025 um 20:21 Uhr schrieb mooi-zestien <
***@***.***>:

**Comment by webpatrick** [comment]
@mooi-zestien you can use codeblocks in comments:

```yaml
- sensor:
  - name: "solax_energy"
    unique_id: 0a27984d-Uniek-540e776f2df0
    device_class: energy
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    state: >
    {% if is_state('sensor.yield_total', 'unavailable') %}{{none}}{% else %}
    {{ ((states('sensor.yield_total') | float(default=0)) / 1) | round(2, default=0) }}
    {% endif %}
- sensor:
  - name: "solax_today"
    unique_id: 0a27984d-Uniek-540e776f2df1
    device_class: energy
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    state: >
    {% if is_state('sensor.yield_today', 'unavailable') %}{{none}}{% else %}
    {{ ((states('sensor.yield_today') | float(default=0)) / 1) | round(2, default=0) }}
    {% endif %}
```

And you could also create 2 helpers via the interface to achieve this:
Go to Settings > Devices & services > Helpers
Create Helper and choose Template > Template a sensor and fill in the above values in the appropriate fields.

But it would be better if @frank8the9tank could add the `state_class` to the appropriate sensors
